name: Generate Telegram DC Configs

on:
  schedule:
    # UTC+8 每周五 6:00 = UTC 每周四 22:00
    - cron: "0 22 * * 4"
  workflow_dispatch: # 允许手动触发

# 添加必要的权限
permissions:
  contents: write # 允许创建和修改 releases
  packages: write # 允许上传文件

jobs:
  generate-configs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的 git 历史

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Generate config files
        env:
          cfid: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          cfsecret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
        run: python main.py

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            telegramSG.conf
            telegramUS.conf
            telegramEU.conf
            dc_assignments.json
          tag_name: v$(date +'%Y.%m.%d')
          name: Telegram DC Configs $(date +'%Y-%m-%d')
          body: |
            Telegram DC configuration files generated on $(date +'%Y-%m-%d %H:%M:%S UTC+8')

            Files included:
            - telegramSG.conf (Singapore DC)
            - telegramUS.conf (Miami DC)
            - telegramEU.conf (Amsterdam DC)
            - dc_assignments.json (Detailed analysis)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
